-- MySQL Script generated by MySQL Workbench
-- Sat Oct 25 17:14:58 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ns_osr89909
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ns_osr89909
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ns_osr89909` DEFAULT CHARACTER SET utf8 ;
USE `ns_osr89909` ;

-- -----------------------------------------------------
-- Table `ns_osr89909`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ns_osr89909`.`Customers` (
  `idCustomers` INT NOT NULL,
  `FirstName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Phone` VARCHAR(45) NULL,
  `DefaultAddressID` INT UNSIGNED NULL,
  `CreatedAt` DATETIME NULL,
  PRIMARY KEY (`idCustomers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ns_osr89909`.`Addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ns_osr89909`.`Addresses` (
  `idAddresses` INT NULL,
  `Street` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `State` VARCHAR(45) NULL,
  `Zip` VARCHAR(45) NULL,
  `Notes` VARCHAR(45) NULL,
  `Customers_idCustomers` INT NOT NULL,
  INDEX `fk_Addresses_Customers_idx` (`Customers_idCustomers` ASC) VISIBLE,
  CONSTRAINT `fk_Addresses_Customers`
    FOREIGN KEY (`Customers_idCustomers`)
    REFERENCES `ns_osr89909`.`Customers` (`idCustomers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ns_osr89909`.`Employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ns_osr89909`.`Employees` (
  `idEmployees` INT NOT NULL,
  `FirstName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Role` VARCHAR(45) NULL,
  `HireDate` DATE NULL,
  PRIMARY KEY (`idEmployees`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ns_osr89909`.`Artists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ns_osr89909`.`Artists` (
  `idArtists` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `PayRatePerDesign` DECIMAL(10,2) NULL,
  `Bio` VARCHAR(45) NULL,
  PRIMARY KEY (`idArtists`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ns_osr89909`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ns_osr89909`.`Products` (
  `idProducts` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `PieceCount` INT NULL,
  `UnitPrice` DECIMAL(10,2) NULL,
  `SKU` VARCHAR(45) NULL,
  `IsCustom` TINYINT NULL,
  `CreatedAt` DATETIME NULL,
  `Artists_idArtists` INT NOT NULL,
  PRIMARY KEY (`idProducts`),
  INDEX `fk_Products_Artists1_idx` (`Artists_idArtists` ASC) VISIBLE,
  CONSTRAINT `fk_Products_Artists1`
    FOREIGN KEY (`Artists_idArtists`)
    REFERENCES `ns_osr89909`.`Artists` (`idArtists`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ns_osr89909`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ns_osr89909`.`Categories` (
  `idCategories` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategories`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ns_osr89909`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ns_osr89909`.`Orders` (
  `idOrders` INT NOT NULL,
  `OrderDate` DATE NULL,
  `TotalCost` DECIMAL(10,2) NULL,
  `Status` VARCHAR(45) NULL,
  `Notes` VARCHAR(45) NULL,
  `Customers_idCustomers` INT NOT NULL,
  PRIMARY KEY (`idOrders`),
  INDEX `fk_Orders_Customers1_idx` (`Customers_idCustomers` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_Customers1`
    FOREIGN KEY (`Customers_idCustomers`)
    REFERENCES `ns_osr89909`.`Customers` (`idCustomers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ns_osr89909`.`Order_Items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ns_osr89909`.`Order_Items` (
  `idOrder_Items` INT NOT NULL,
  `UnitPriceAtSale` VARCHAR(45) NULL,
  `Orders_idOrders` INT NOT NULL,
  `Products_idProducts` INT NOT NULL,
  `Quantity` INT NULL,
  PRIMARY KEY (`idOrder_Items`),
  INDEX `fk_Order_Items_Orders1_idx` (`Orders_idOrders` ASC) VISIBLE,
  INDEX `fk_Order_Items_Products1_idx` (`Products_idProducts` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Items_Orders1`
    FOREIGN KEY (`Orders_idOrders`)
    REFERENCES `ns_osr89909`.`Orders` (`idOrders`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Items_Products1`
    FOREIGN KEY (`Products_idProducts`)
    REFERENCES `ns_osr89909`.`Products` (`idProducts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ns_osr89909`.`Custom_Order_Requests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ns_osr89909`.`Custom_Order_Requests` (
  `idCustom_Order_Requests` INT NOT NULL,
  `ImageLink` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  `Status` VARCHAR(45) NULL,
  `SubmittedAt` DATETIME NULL,
  `ReviewedAt` DATETIME NULL,
  `Notes` VARCHAR(45) NULL,
  `Customers_idCustomers` INT NOT NULL,
  `Employees_idEmployees` INT NOT NULL,
  `Products_idProducts` INT NOT NULL,
  `ApprovedProductID` VARCHAR(45) NULL,
  PRIMARY KEY (`idCustom_Order_Requests`),
  INDEX `fk_Custom_Order_Requests_Customers1_idx` (`Customers_idCustomers` ASC) VISIBLE,
  INDEX `fk_Custom_Order_Requests_Employees1_idx` (`Employees_idEmployees` ASC) VISIBLE,
  INDEX `fk_Custom_Order_Requests_Products1_idx` (`Products_idProducts` ASC) VISIBLE,
  CONSTRAINT `fk_Custom_Order_Requests_Customers1`
    FOREIGN KEY (`Customers_idCustomers`)
    REFERENCES `ns_osr89909`.`Customers` (`idCustomers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Custom_Order_Requests_Employees1`
    FOREIGN KEY (`Employees_idEmployees`)
    REFERENCES `ns_osr89909`.`Employees` (`idEmployees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Custom_Order_Requests_Products1`
    FOREIGN KEY (`Products_idProducts`)
    REFERENCES `ns_osr89909`.`Products` (`idProducts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ns_osr89909`.`Product_Images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ns_osr89909`.`Product_Images` (
  `idProduct_Images` INT NOT NULL,
  `ImageURL` VARCHAR(45) NULL,
  `AltText` VARCHAR(45) NULL,
  `IsPrimary` TINYINT NULL,
  `Products_idProducts` INT NOT NULL,
  PRIMARY KEY (`idProduct_Images`),
  INDEX `fk_Product_Images_Products1_idx` (`Products_idProducts` ASC) VISIBLE,
  CONSTRAINT `fk_Product_Images_Products1`
    FOREIGN KEY (`Products_idProducts`)
    REFERENCES `ns_osr89909`.`Products` (`idProducts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ns_osr89909`.`Payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ns_osr89909`.`Payments` (
  `idPayments` INT NOT NULL,
  `MethodOfPayment` VARCHAR(45) NULL,
  `Amount` DECIMAL(10,2) NULL,
  `TransactionRefNumber` VARCHAR(45) NULL,
  `PaymentDate` DATE NULL,
  `Orders_idOrders` INT NOT NULL,
  PRIMARY KEY (`idPayments`),
  INDEX `fk_Payments_Orders1_idx` (`Orders_idOrders` ASC) VISIBLE,
  CONSTRAINT `fk_Payments_Orders1`
    FOREIGN KEY (`Orders_idOrders`)
    REFERENCES `ns_osr89909`.`Orders` (`idOrders`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ns_osr89909`.`Products_Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ns_osr89909`.`Products_Categories` (
  `Products_idProducts` INT NOT NULL,
  `idCategories` INT NOT NULL,
  PRIMARY KEY (`Products_idProducts`, `idCategories`),
  INDEX `fk_ProductsCategories_Categories_idx` (`idCategories` ASC) VISIBLE,
  CONSTRAINT `fk_ProductsCategories_Products`
    FOREIGN KEY (`Products_idProducts`)
    REFERENCES `ns_osr89909`.`Products` (`idProducts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductsCategories_Categories`
    FOREIGN KEY (`idCategories`)
    REFERENCES `ns_osr89909`.`Categories` (`idCategories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
